### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by yaroslav207** [yaroslav207/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by maks2077** [comment]
Н А В Ы К И

Сижу; лежу; лижу; даю лапу (и даже две!); приношу мячик, палку, тапки и радость; громко лаю, грозно рычу и "подпеваю" старым песням Кобзона; одной силой мысли (и жалобного взгляда) способен заставить хозяина выдать мне двойную порцию вкусняшек; провожаю на работу; слежу за котом; встречаю с работы; помогаю выполнять вот такие вот тестовые задания за еду и, конечно же, профессионально люблю всех приближённых мне кожаных.

Х А Р А К Т Е Р

Представьте себе идеального компаньона?
Представили?
А теперь забудьте, потому что я высячу раз лучше любого из них!
Преданность, острый ум, сногшибательная красота и, конечно же, непомераня скромность – все эти качества собраны в одном пушистом флаконе и имя ему, как Вы, я уверен, уже успели догадаться, Джером.
 
Н Р А В И Т С Я

Спать на диване; смотреть "101 долматинец" сутками напролёт; грызть неправильно положенный линолеум; гулять в парке и лаять на тень.
 
Н Е Н Р А В И Т С Я

Ходить к ветеринару (вы вообще в курсе, куда они вставляют градусник?!), сидеть в одиночестве и когда кот начинает играться с моим хвостом.
