### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by yaroslav207** [yaroslav207/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by maks2077** [comment]
Йо!
Я настолько хороший мальчик, что хозяин считает жизненно необходимым запечатлеть все мои достижения в моём собственном резюме.
Ознакомившись с ним до конца у Вас не останется сомнений в том, что он поступил правильно, а я лучше Рю из Street Fighter и, уж точно, в десять раз круче какого-то там Дональда Трампа.

*Я пока ещё не научился печатать, но со всей ответственностью заявляю, что всё ниже указанное было с точностью воспроизведено с моих слов.
