### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by yaroslav207** [yaroslav207/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by yaroslav207** [comment]
https://www.instagram.com/mr.jeronimodog/

+380954457482

yaroslav.sprynsian8@gmail.com

**Comment by maks2077** [comment]
https://www.instagram.com/mr.jeronimodog/

+380954457482

yaroslav.sprynsian8@gmail.com
