### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by yaroslav207** [yaroslav207/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by maks2077** [comment]
Началась моя история 15-го февраля 2019-го года в небольшой деревне под Харьковом, правда тогда я об этом ещё не знал – понимал только, что вокруг достаточно тепла, чтобы не мёрзнуть и вдоволь молока, чтобы отрастить круглый пузик.

1-го марта я впервые открыл глаза и увидел весну. Хотя об этом я тоже тогда был не в курсе: для меня ничего другого никогда и не существовало. Зато я обнаружил, что, помимо меня, вокруг мамы ползало ещё девять моих братьев.По секрету – я был из них самым красивым.

16-го марта нас, на конец-то, выпустили во двор. Вокруг было много места и ещё больше света, но самое интересное творилось у нас под ногами – эта белая штука, люди назвали её снегом, просто улёт! Сейчас я уже знаю, что он падает с неба тогда, когда хозяин напяливает на уши шапку. Обожаю вывалять свои бока в сугробе – это так освежает.

4-го апреля 2019-года случилось второе перевернувшее мою жизнь с ног на голову событие – к нам в гости пришли какие-то люди. Они долго ходили, чего-то высматривали и о чем-то переговаривались между собой. Вот тогда-то я и решил, что нужно брать всё в свои лапы и обмочил ботинок этого нерешительного человека. Так он стал моим, но, чтобы его не обидеть, я формально зову его своим хозяином.

С 4-го апреля и по сегодняшний день я гордо несу звание полноправного члена семьи, великого защитника, стоящего на страже порядка и лучшего друга своих лучших-в-мире хозяев.
 
Ниже приведён короткий список моих наиболее значимых достижений на "работе" в этой прекрасной компании.
 
20-го апреля 2019 года – стойко перенёс базовый набор прививок и получил свой первый ветеринарный паспорт.

6-е мая 2019 года – мне подарили мой первый поводок и красивый ошейник, а потом вывели на премьерную прогулку (этот город оказался гораздо больше того двора, который я видел в детстве!)
 
1 июня 2019 года – я стал почётным студентом Харьковского кинелогичного центра "KINOLOG", откуда выпустился с отличием через пять месяцев 20-го ноября.

26-го февраля 2020-го года – спустя долгие десять месяцев военных действий, на конец, заключил пакт перемирия с нашим котом Паскалем и до сих пор придерживаюсь установленный правил.

2-го марта 2021 года –к моему дресскоду прибавили этот ужасный намордник, но я до сих пор надеюсь, что это последствия этой дурацкой пандемии и в скором времени я смогу избавиться от этой надоедливой "маски".
